### ISSUE TITLE
HFC

### ISSUE THREAD

**Issue by bujowskis** [bujowskis/mk-convection-selection-22-23#27]
Hierarchical Fair Competition

- (to be used later on)
- Similar to ConvSel, with some differences, it would be best if the differences were parameters of ConvSel, so depending on the parametrization the algorithm if either ConvSel, HFC, or something in between

Description: [Article](https://drive.google.com/file/d/1XI1p5CiWTVcgzPiBgKKXUSb0-4IlgrNB/view)

**Comment by aksenyuk** [comment]
- stick to the alternative option described in point 5b) III from [HTC in a nutshell](https://docs.google.com/document/d/1xQeeqMcjfHedGTZAeyR9V-pp9mODfA_KzrBi2-rHBf8/edit)
- buffer has no size
- add individuals to the population from the buffer randomly
- compare HFC and CS based on the same parameters
- after migration, the buffer unconditionally gets emptied
- add a mechanism that checks the removal of ___too many___ individuals
- initially sample random solutions of initial population size, so that the admission threshold is the average of fitness values of it
- the best and the worst populations are the only ones of different widths (however, we can set all subpopulations' widths to be equal for the sake of similarity with CS)
- set the initial genotype to "X" and mutate it in a loop until there are, e.g., 5 neurons and/or 5 body parts (OR just until len(genotype) == 10)
- set samples = 1, defining CEC benchmark functions
- ___special value___ of the algorithms' performance to track will be sent by Konrad a bit later
